apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
resources:
  - networkpolicy.yaml
  - model-config.yaml
  - remote-mcp-web-search.yaml
  - remote-mcp-graphiti-memory.yaml
