apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: infra-ai-mvp
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-ai-mvp
  source:
    repoURL: https://github.com/YounssBrag/Infra-ai-Agentic-systems.git
    targetRevision: HEAD
    path: infra-code/platform/kong/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
