apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: infra-ai-mvp

servers: 1
agents: 0

image: rancher/k3s:v1.30.6-k3s1

registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "300s"
    disableLoadbalancer: false
  k3s:
    nodeLabels:
      - label: ingress-ready=true
        nodeFilters:
          - server:*
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
