apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.5.0/manifests/install.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      - op: add
        path: /data
        value:
          server.insecure: "true"
          application.namespaces: "argocd"
          controller.status.processors: "5"
          controller.operation.processors: "3"
          reposerver.parallelism.limit: "2"

  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports
        value:
          - name: http
            port: 80
            targetPort: 8080
            nodePort: 30081
            protocol: TCP
          - name: https
            port: 443
            targetPort: 8080
            protocol: TCP

  - target:
      kind: Deployment
      name: argocd-dex-server
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0

  - target:
      kind: Deployment
      name: argocd-notifications-controller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0

  - target:
      kind: Deployment
      name: argocd-applicationset-controller
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0

  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: "1"
            memory: 384Mi

  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: "1"
            memory: 384Mi

  - target:
      kind: Deployment
      name: argocd-redis
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi

  - target:
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "2"
            memory: 512Mi
