---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ai-gateway
  labels:
    app.kubernetes.io/part-of: infra-ai-mvp
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_ME_DO_NOT_COMMIT"
  JWT_ISS: "mvp-app"
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-api
  namespace: ai-gateway
  labels:
    app.kubernetes.io/part-of: infra-ai-mvp
type: Opaque
stringData:
  GOOGLE_API_KEY: "REPLACE_ME_DO_NOT_COMMIT"
