apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-ai-mvp
  source:
    repoURL: https://github.com/Yoiness-Brag/Infra-ai-Agentic-systems.git
    targetRevision: platform-v2
    path: infra-code/platform/data
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - '.spec.volumeClaimTemplates[]?.metadata.creationTimestamp'
        - '.spec.volumeClaimTemplates[]?.status'
        - '.spec.volumeClaimTemplates[]?.apiVersion'
        - '.spec.volumeClaimTemplates[]?.kind'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
