apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-ai-mvp
  sources:
    - repoURL: https://charts.konghq.com
      chart: kong
      targetRevision: 3.4.1
      helm:
        releaseName: kong
        valueFiles:
          - $values/infra-code/platform/kong/values.yaml
    - repoURL: https://github.com/Yoiness-Brag/Infra-ai-Agentic-systems.git
      targetRevision: platform-v2
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
